FROM ace_v13:latest
ARG BAR_FILE
ENV BAR_NAME=${BAR_FILE}
ENV LICENSE=accept
USER root
RUN mkdir -p /home/aceuser/bars /home/aceuser/ace-server && chown -R aceuser:aceuser /home/aceuser/
COPY --chown=aceuser:aceuser ${BAR_NAME} /home/aceuser/bars/
RUN . /opt/ibm/ace-13/server/bin/mqsiprofile && \
    mqsibar -w /home/aceuser/ace-server -a /home/aceuser/bars/${BAR_NAME} -c
USER aceuser
EXPOSE 7800 7600
CMD ["IntegrationServer", "--name", "ACEServer", "--work-dir", "/home/aceuser/ace-server"]